[tasks."auth:ecr"]
run = "aws ecr get-login-password | docker login --username AWS --password-stdin 254820071958.dkr.ecr.us-west-2.amazonaws.com"

[tasks."auth:ca"]
run = "export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain phylactery --domain-owner 254820071958 --query authorizationToken --output text`"

[tasks."auth"]
depends = ["auth:*"]

[tools]
go = "1.22"
node = ["20", "18"]
python = "3.11"
rust = "latest"
terraform = ["1.5.1"]

"cargo:ubi" = "latest"
"npm:biome" = "latest"
"npm:prettier" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"
"ubi:evilmartians/lefthook" = "latest"
# "ubi:tamasfe/taplo" = "latest"  # Doesn't include LSP. Need "full"
