#!/usr/bin/env bash

set -e

CONFIG="install.yaml"
DOTBOT_DIR=".dotbot"
PLUGIN_DIR=".dotbot-plugins"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${PLUGIN_DIR}"

python3 "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" \
  -d "${BASEDIR}" \
  -c "${CONFIG}" \
  --plugin-dir "${PLUGIN_DIR}/dotbot-stow" \
  "${@}"
