#:schema https://mise.jdx.dev/schema/mise.json
[settings]
auto_env = true

[bootstrap.hooks]
pre-dotfiles = """
mkdir -p ~/.config/fish/functions
mkdir -p ~/.config/gh
mkdir -p ~/.config/karabiner
"""

[dotfiles]
"~/.config" = { mode = "symlink-each", source = "~/git/qbedard/dotfiles/config" }

# [tasks."upgrade:brew"]
# run = "brew upgrade --quiet"

[tasks."upgrade:brew-casks"]
run = "brew upgrade --cask --quiet"

[tasks."upgrade:mise"]
run = "mise upgrade --quiet"

[tasks."upgrade:mise-packages"]
run = "mise bootstrap packages upgrade --jobs 1 --yes"

[tasks."upgrade:nvim"]
run = "nvim --headless '+Lazy! sync' +MasonUpdate +TSUpdate +qa"

[tasks.upgrade]
depends = ["upgrade:*"]
