#:schema https://mise.jdx.dev/schema/mise.json
[settings]
auto_env = true

[bootstrap.hooks]
pre-dotfiles = """
mkdir -p ~/.claude
mkdir -p ~/.config/fish/functions
mkdir -p ~/.config/gh
mkdir -p ~/.config/karabiner
mkdir -p ~/Library/Application Support/biome
mkdir -p ~/Library/Application Support/jesseduffield/lazydocker
mkdir -p ~/Library/Application Support/pypoetry
"""

[dotfiles]
"~/.config" = { mode = "symlink-each", source = "~/git/qbedard/dotfiles/config" }

[tasks.install]
description = "Install dotfiles using Dotbot"
run = "./install"

[tasks.link]
run = "./install --only clean create link stow"

[tasks.update-mise-packages]
run = "mise bootstrap packages upgrade"

[tasks."update:brew"]
run = "brew upgrade --quiet"

[tasks."update:mise"]
run = "mise upgrade --quiet"

# [tasks."update:tldr"]
# run = "tldr --update"

[tasks."update:nvim"]
run = "nvim --headless '+Lazy! sync' +MasonUpdate +TSUpdate +qa"

[tasks.update]
depends = ["update:*"]
