format = "$all"

[aws]
disabled = true

[cmd_duration]
# TODO: Figure out how to fix timer icons being kanji
format = "[ $duration]($style) "

[directory]
read_only_symbol = ""

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
deleted = "x"
# TODO: Flesh these out
# format = "[($all_status)($ahead_behind)]($style) "
# conflicted = ""
# ahead = ""
# behind = ""
# diverged = ""
# untracked = ""
# stashed = ""
# modified = ""
# staged = ""
# renamed = ""
# deleted = ""

[golang]
format = "[$symbol$version]($style) "
symbol = " "

[line_break]
disabled = true

[nodejs]
format = "[$symbol$version]($style) "

[package]
disabled = true

[python]
format = "[$symbol($virtualenv )]($style)"
symbol = " "

[rust]
format = "[$symbol$version]($style) "
symbol = " "
