format = "$all"
add_newline = false

[aws]
symbol = " "
disabled = true

[cmd_duration]
# TODO: Figure out how to fix timer icons being kanji
format = "[ $duration]($style) "
disabled = true

[directory]
read_only = " "

[docker]
symbol = " "

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
deleted = "x"
# TODO: Flesh these out
# format = "[($all_status)($ahead_behind)]($style) "
# conflicted = ""
# ahead = ""
# behind = ""
# diverged = ""
# untracked = ""
# stashed = ""
# modified = ""
# staged = ""
# renamed = ""
# deleted = ""

[golang]
format = "[$symbol$version]($style) "
symbol = " "

[java]
symbol = " "

[line_break]
disabled = true

[nodejs]
format = "[$symbol$version]($style) "

[package]
symbol = " "
disabled = true

[python]
format = "[$symbol($virtualenv )]($style)"
symbol = " "

[ruby]
format = "[$symbol$version]($style) "
symbol = " "

[rust]
format = "[$symbol$version]($style) "
symbol = " "

[shlvl]
format = "[$symbol]($style)"
symbol = "↳"
disabled = false

[terraform]
format = "[$symbol$version]($style) "
symbol = " "
disabled = true

[vagrant]
format = "[$symbol$version]($style)"
