format = "$all"

[aws]
disabled = true

[cmd_duration]
# TODO: Figure out how to fix timer icons being kanji
format = "[ $duration]($style) "

[git_branch]
format = "[$symbol$branch]($style) "

[golang]
format = "[$symbol$version]($style) "
symbol = " "

[line_break]
disabled = true

[nodejs]
format = "[$symbol$version]($style) "

[package]
disabled = true

[python]
format = "[$symbol(@$virtualenv )]($style)"
symbol = " "

[rust]
format = "[$symbol$version]($style) "
symbol = " "
