export ZSH=${HOME}/.oh-my-zsh
ZSH_THEME="kolo"

plugins=(
    aws
    fasd
    docker
    docker-compose
    # gem
    git
    osx
    pip
    python
    redis-cli
    sudo
    # tmux
    vagrant
    web-search
    zsh-autosuggestions
    zsh-syntax-highlighting
    )

source $ZSH/oh-my-zsh.sh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

source $HOME/.dotfiles/shell/common.sh

if hash direnv 2>/dev/null; then
    eval "$(direnv hook zsh)"
fi

# Vim keybindings
# bindkey -v
# export KEYTIMEOUT=1
