return {
  "timbedard/vim-envelop",
  build = ":EnvCreate",
  config = function()
    vim.g.envelop_enabled = { "node", "python3" }
    vim.g.envelop_node_link = {
      "node_modules/.bin/prettier",
      -- "node_modules/.bin/bash-language-server",
      -- "node_modules/.bin/docker-langserver",
      "node_modules/.bin/neovim-node-host",
      -- "node_modules/.bin/pyright",
      -- "node_modules/.bin/pyright-langserver",
      "node_modules/.bin/sql-formatter",
      -- "node_modules/.bin/typescript-language-server",
      -- "node_modules/.bin/vim-language-server",
      -- "node_modules/.bin/vscode-css-language-server",
      -- "node_modules/.bin/vscode-html-language-server",
      -- "node_modules/.bin/vscode-json-language-server",
      -- "node_modules/.bin/yaml-language-server",
    }
    vim.g.envelop_node_packages = {
      -- "bash-language-server",
      -- "dockerfile-language-server-nodejs",
      "neovim",
      "prettier",
      -- "pyright",
      "sql-formatter",
      -- "typescript",
      -- "typescript-language-server",
      -- "vim-language-server",
      -- "vscode-langservers-extracted",
      -- "yaml-language-server",
    }
    vim.g.envelop_python3_link = {
      "bin/autoflake",
      "bin/bandit",
      "bin/black",
      "bin/docformatter",
      "bin/flake8",
      "bin/isort",
      -- "bin/mypy",
      "bin/pip3",
      "bin/pydocstyle",
      "bin/python3",
      "bin/sqlfluff",
      "bin/sqlformat",
      "bin/vint",
    }
    vim.g.envelop_python3_packages = {
      "autoflake",
      "bandit",
      "black",
      "docformatter",
      "flake8",
      "flake8-bugbear",
      -- "flake8-builtins",
      -- "flake8-docstrings",
      -- "flake8-pytest-style",
      -- "flake8-simplify",
      "isort",
      -- "mypy",
      "pep8-naming",
      "pip",
      "pydocstyle",
      "pynvim",
      "sqlfluff",
      "sqlparse",
      "vim-vint",
    }
  end,
}
