return {
  "timbedard/vim-envelop",
  -- lazy = false,
  enable = false,
  build = ":EnvCreate",
  init = function()
    vim.g.envelop_enabled = { "python3" }
    vim.g.envelop_python3_link = {
      -- "bin/autoflake",
      "bin/bandit",
      -- "bin/black",
      "bin/docformatter",
      "bin/flake8",
      -- "bin/isort",
      -- "bin/mypy",
      "bin/pip3",
      -- "bin/pydocstyle",
      "bin/python3",
      -- "bin/sqlfluff",
      -- "bin/sqlformat",
      -- "bin/vint",
    }
    vim.g.envelop_python3_packages = {
      -- "autoflake",
      "bandit",
      -- "black",
      "docformatter",
      "flake8",
      "flake8-bugbear",
      -- "flake8-builtins",
      -- "flake8-docstrings",
      -- "flake8-pytest-style",
      -- "flake8-simplify",
      -- "isort",
      -- "mypy",
      "pep8-naming",
      "pip",
      -- "pydocstyle",
      "pynvim",
      -- "sqlfluff",
      -- "sqlparse",
      -- "vim-vint",
    }
  end,
}
