#:schema https://mise.jdx.dev/schema/mise.json
[bootstrap.packages]
"brew:awscli" = "latest"
"brew:gnupg" = "latest" # GPG tools
"brew:opa" = "latest"
"brew:terraform-ls" = "latest"
"brew:terraform-mcp-server" = "latest"

# --- Casks --- #
# "brew-cask:docker" = "latest"

[env]
SAM_CLI_TELEMETRY = 0

[tools]
node = { version = "24", postinstall = "corepack enable" }

# "github:open-policy-agent/opa" = "latest"
"npm:@actions/languageserver" = "latest"
# "npm:semantic-release" = "latest"
# "npm:snyk" = "latest"
"pipx:mcp-atlassian" = "latest"
# "pipx:awslabs.aws-api-mcp-server" = "latest"
# "pipx:checkov" = "latest"
