[bootstrap.hooks]
pre-dotfiles = """
mkdir -p ~/Library/Application Support/biome
mkdir -p ~/Library/Application Support/jesseduffield/lazydocker
mkdir -p ~/Library/Application Support/pypoetry
"""
post-defaults = "killall Dock Finder SystemUIServer || true"

[bootstrap.macos.defaults.NSGlobalDomain]
AppleKeyboardUIMode = 3
AppleShowAllExtensions = true
InitialKeyRepeat = 12
KeyRepeat = 1
"com.apple.mouse.tapBehavior" = 0

[bootstrap.macos.defaults."com.apple.dock"]
autohide = true
autohide-delay = 1000
mru-spaces = false
no-bouncing = true
orientation = "left"

[bootstrap.macos.defaults."com.apple.finder"]
AppleShowAllFiles = true
ShowPathbar = true
_FXShowPosixPathInTitle = true
_FXSortFoldersFirst = true

[bootstrap.macos.defaults."com.apple.screensaver"]
askForPassword = 1
askForPasswordDelay = 0

[bootstrap.macos.defaults."com.apple.TimeMachine"]
DoNotOfferNewDisksForBackup = true

[bootstrap.macos.trackpad]
tap_to_click = false

[bootstrap.packages]
# --- mas --- # TODO
# "brew:mas" = "latest"
# "mas:497799835" = "latest" # Xcode

# --- Homebrew --- #
"brew:bat" = "latest" # cat replacement
"brew:coreutils" = "latest" # GNU coreutils (macOS utils are a little different)
"brew:diff-so-fancy" = "latest" # fancy git diff
"brew:eza" = "latest" # ls replacement
"brew:fd" = "latest" # find replacement
"brew:fish" = "latest" # shell
"brew:fzf" = "latest" # fuzzy
"brew:gh" = "latest" # GitHub CLI
"brew:git" = "latest"
"brew:go" = "latest"
# "brew:ipython" = "latest" # better python shell
"brew:jq" = "latest" # JSON parsing
"brew:lua-language-server" = "latest"
# brew 'luajit', args: ['HEAD'] # neovim HEAD dep
# "brew:mise" = "latest" # tool version manager TODO: have this here?
"brew:neovim" = "latest"
# "brew:procs" = "latest" # ps replacement
"brew:ripgrep" = "latest" # awesome grep
"brew:shellcheck" = "latest" # used by bashls
"brew:shfmt" = "latest"
"brew:starship" = "latest" # shell prompt
# "brew:stow" = "latest"
"brew:stylua" = "latest"
"brew:taplo" = "latest" # TOML LSP and toolset
# "brew:tealdeer" = "latest"  # Rust tldr pages client
"brew:tldr" = "latest"
# "brew:tree-sitter-cli" = "latest"  # for Neovim parsers
"brew:tokei" = "latest" # fancy line count
"brew:uv" = "latest"
"brew:zoxide" = "latest" # fast dir nav

# # --- Casks --- #
# "brew-cask:amethyst" = "latest" # tiling window manager
# "brew-cask:kitty" = "latest" # terminal
# "brew-cask:sol" = "latest" # Spotlight replacement
#
# # --- Fonts --- #
# "brew-cask:font-iosevka" = "latest"
# "brew-cask:font-symbols-only-nerd-font" = "latest"

[bootstrap.user]
login_shell = "/opt/homebrew/bin/fish"

[dotfiles."~/Library/Application Support/biome/biome.json"]
source = "~/git/qbedard/dotfiles/config/biome.json"

[dotfiles."~/Library/Application Support/jesseduffield/lazydocker/config.yml"]
source = "~/git/qbedard/dotfiles/lazydocker-config.yaml"

[dotfiles."~/Library/Application Support/pypoetry/config.toml"]
source = "~/git/qbedard/dotfiles/config/pypoetry/config.toml"
