#:schema https://mise.jdx.dev/schema/mise.json
[settings]
dotfiles.root = "~/git/qbedard/dotfiles"
experimental = true
idiomatic_version_file_enable_tools = [
  "go",
  "node",
  "python",
  "terraform",
  "yarn",
]

[bootstrap.hooks]
pre-dotfiles = """
mkdir -p ~/.claude
mkdir -p ~/.config/fish/functions
mkdir -p ~/.config/gh
mkdir -p ~/.config/karabiner
"""
post-packages = "bat cache --build"

[bootstrap.mise_shell_activate]
bash = true
# fish = true
zsh = true

[dotfiles]
"~/.claude" = { mode = "symlink-each", source = "~/git/qbedard/dotfiles/claude" }
"~/.config" = { mode = "symlink-each", source = "~/git/qbedard/dotfiles/config" }
"~/.amethyst.yml" = "~/git/qbedard/dotfiles/amethyst.yaml"
"~/.bashrc" = "~/git/qbedard/dotfiles/bashrc"
"~/.common.sh" = "~/git/qbedard/dotfiles/common.sh"
"~/.hushlogin" = "~/git/qbedard/dotfiles/hushlogin"
"~/.npmrc" = "~/git/qbedard/dotfiles/npmrc"
"~/.ripgreprc" = "~/git/qbedard/dotfiles/ripgreprc"
"~/.sql-formatter.json" = "~/git/qbedard/dotfiles/sql-formatter.json"
"~/.tflint.hcl" = "~/git/qbedard/dotfiles/tflint.hcl"
"~/.zshrc" = "~/git/qbedard/dotfiles/zshrc"

# TODO: [shell_alias]

[env]
PYTHONDONTWRITEBYTECODE = 1 # prevent .pyc files

[tools]
go = "latest"
python = "3.13"
terraform = "latest"
usage = "latest"

"github:astral-sh/uv" = "latest"

"aqua:anthropics/claude-code" = "latest"

"github:astral-sh/ruff" = "latest"
"github:google/yamlfmt" = "latest"
"github:rtk-ai/icm" = "latest"
"github:koalaman/shellcheck" = "latest"
"github:tamasfe/taplo" = { version = "latest" }

"go:golang.org/x/tools/gopls" = "latest"
"npm:@biomejs/biome" = "latest"
# "npm:tree-sitter-cli" = "latest"
"npm:prettier" = "latest"
"pipx:poetry" = "latest"
"pipx:pre-commit" = "latest"
"pipx:pyright" = "latest"
"pipx:ty" = "latest"

# [tools."github:usagi-flow/evil-helix"]
# version = "latest"
# extract_all = "true"
