[lint]
select = [
  "A",
  "B",
  "C4",
  "C90",
  "D",
  "E",
  "F",
  "N",
  "PIE",
  "PT003",
  "PT006",
  "PT008",
  "PT022",
  "RET504",
  "SIM",
  "T20",
  "UP",
  "W",
]
ignore = [
  "D1",
  "D203",
  "D205",
  "D212",
  "D213",
  "D400",
  "D404",
  "D415",
  "I",
  "N818",
]

[isort]
lines-after-imports = 2

[format]
preview = true
