[lint]
select = [
  "A", # flake8-builtins
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "C90", # mccabe
  "D",
  "E", # pycodestyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8-naming
  "W", # pycodestyle warnings
  "PIE", # flake8-pie
  "PT003",
  "PT006",
  "PT008",
  "PT022",
  "RET504", # flake8-return -> unnecessary-assign
  "SIM", # flake8-simplify
  "T20", # flake8-print
  "UP", # pyupgrade
]
ignore = [
  "D1",
  "D203",
  "D205",
  "D212",
  "D213",
  "D400",
  "D404",
  "D415",
  "N818",
]

[lint.isort]
lines-after-imports = 2

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
# preview = true
